# Generated by Django 2.2 on 2020-12-21 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user_books_likes',
            field=models.ManyToManyField(related_name='book_likes', to='app1.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_comment_likes',
            field=models.ManyToManyField(related_name='commnet_likes', to='app1.User'),
        ),
        migrations.AddField(
            model_name='wall_message',
            name='user_message_likes',
            field=models.ManyToManyField(related_name='message_likes', to='app1.User'),
        ),
    ]
